steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - backend/market_scout/Dockerfile.weekly_preprocess
      - -t
      - asia-southeast1-docker.pkg.dev/$PROJECT_ID/market-scout/careerviet-preprocess:job2
      - .
images:
  - asia-southeast1-docker.pkg.dev/$PROJECT_ID/market-scout/careerviet-preprocess:job2
