steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - backend/market_scout/Dockerfile.weekly_trend_facts
      - -t
      - asia-southeast1-docker.pkg.dev/$PROJECT_ID/market-scout/careerviet-trend-facts:job3
      - .
images:
  - asia-southeast1-docker.pkg.dev/$PROJECT_ID/market-scout/careerviet-trend-facts:job3
